- name: Add Google Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present 

- name: Add Google Chrome's repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Google Chrome
  apt:
    pkg:
      - google-chrome-stable
    state: present    

- name: Add Mattermost's signing key
  ansible.builtin.apt_key:
    url: https://deb.packages.mattermost.com/pubkey.gpg
    state: present 

- name: Add Mattermost
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://deb.packages.mattermost.com stable main
    state: present
    filename: mattermost

- name: Install Mattermost
  apt:
    pkg:
      - mattermost-desktop
    state: present  